### PR TITLE
Make hoistStatics optional, change "duplicate" errors to warnings

### LINKED ISSUE #1: Do not hoist statics
This library should not hoist statics, because it named as "hoist-non-react-methods"

### PR DESCRIPTION
**Pull request by JulianKingman**
This fixes https://github.com/elado/hoist-non-react-methods/issues/1

I also changed the duplicate errors into console warnings, since overriding the static methods/properties could be done intentionally.

### CODE REVIEW

**Comment by elado** [comment]
Hi @JulianKingman! Thanks for contributing. It looks like you edited the transpiled (Babelled) file instead of the ES6 source. Do you mind editing the original src/index.js? You’ll need to run `npm run build` in order to build it, or you can use `npm run watch` to continiously build on changes.

Also, as a part of the PR please write a test.

Thanks!

**Comment by JulianKingman** [comment]
I'm not sure I understand, where is the original file? The only file I see is src/index.js, which is the one I edited. Are you sure it's added to the repo?

**Comment by elado** [comment]
This is the source file (ES6)
https://github.com/elado/hoist-non-react-methods/blob/master/src/index.js

and here's the compiled file in the node module:
https://unpkg.com/hoist-non-react-methods@1.0.2/lib/index.js

When the package publishes, it transpiles the ES6 source to ES5 using babel, then sends only the transpiled files (lib folder) to npm.
Looks like you directly edited the file in `node_modules` and not the `src/index.js`.

**Comment by JulianKingman** [comment]
I see what you mean, sorry about that! I must have copied and pasted from an existing project that was using the built version.

**Comment by JulianKingman** [comment]
I added the tests. It's my first time writing tests, so apologies if it's messy or if I missed something.

**Comment by JulianKingman** [comment]
@elado can this be merged?

**Comment by JulianKingman** [comment]
@elado Sorry to bug, I'm waiting on this PR to be merged to use this lib in a PR to another repo, if it looks good can you merge it?

**Comment by elado** [comment]
@JulianKingman just released 1.1.0

did it through another PR, also cleaned up a few things
https://github.com/elado/hoist-non-react-methods/pull/4
so closing this

thanks!

**Comment by JulianKingman** [comment]
@elado thanks, you're the best!

**Pull request closed without merging**
